
name: test-workflow

on:
  push:
    branches:
      - master

jobs:
  test-workflow:
    runs-on: ubuntu-latest

  steps:
    - name: Get Repo Owner
      shell: bash
      run: | 
        echo ${{ github.repository_owner }}