
name: test-workflow

on:
  push:
    branches:
      - master

jobs:
  test-workflow:
    runs-on: ubuntu-latest

    if: ${{ github.repository_owner }} != 'test-ghactions'

    steps:
      - name: Test
        shell: bash
        run: | 
          echo ${{ github.repository_owner }}